name: tn
description: location ,ekri,ekri.tn,maison,tunisie,tunisia,sousse,soussa,monastir,sfax,djerba,jerba,libia,algerie,nabeul,klibia,
  appartement.


version: 1.0.5+10

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.0
  flutter_app_badger: ^1.1.2
  animated_splash_screen: ^1.0.0+1
  page_transition: ^1.1.5
  connectivity: ^0.4.2
  carousel_pro: ^1.0.0
  mlkit: ^0.15.1
  google_maps_flutter: ^0.5.26+4
  easy_localization: ^1.3.0+1
  geoflutterfire: ^2.1.0
  location: ^3.0.2
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  shared_preferences: ^0.5.4+5
  image_picker: ^0.6.6+1
  intl: ^0.16.0
  intl_translation: ^0.17.0
  smooth_star_rating: ^1.0.3
  flutter_map_picker: ^0.1.2
  flutter_spinkit: "^4.1.2"
  validated: ^1.0.3
  flutter_google_places: ^0.2.4
  google_maps_webservice: ^0.0.16
  google_place: ^0.3.0
  firebase_database: ^3.1.3
  geolocator: ^5.3.1
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_auth: ^0.15.4
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.1.1
  flutter_password_strength: ^0.1.4
  url_launcher: ^5.4.11
  flutter_blurhash: ^0.5.0
  blurhash: ^0.2.0
  cached_network_image: ^2.2.0+1
  fluttertoast: ^4.0.1
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locale/fr-FR.json
    - assets/locale/ar-FR.json
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family:  Room
      fonts:
        - asset: assets/Room.ttf